import os
import json
import time
from datetime import datetime
from google.transit import gtfs_realtime_pb2

DATA_DIR = "data/processed"
GTFS_DIR = "data/gtfs"
os.makedirs(GTFS_DIR, exist_ok=True)

def build_rt_feed():
    json_path = os.path.join(DATA_DIR, "live_buses.json")
    pb_path = os.path.join(GTFS_DIR, "vehicle_positions.pb")
    
    if not os.path.exists(json_path):
        print(f"[{datetime.now()}] live_buses.json not found. Waiting for crawler.")
        return

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            buses = json.load(f)
    except Exception as e:
        print(f"[{datetime.now()}] Error reading live_buses.json: {e}")
        return

    feed = gtfs_realtime_pb2.FeedMessage()
    feed.header.gtfs_realtime_version = "2.0"
    feed.header.incrementality = gtfs_realtime_pb2.FeedHeader.FULL_DATASET
    feed.header.timestamp = int(time.time())

    for bus in buses:
        route_code = bus.get("route_code")
        direction = bus.get("direction")
        lat = bus.get("lat")
        lon = bus.get("lon")
        plate = bus.get("plate", "UNKNOWN")

        if not (route_code and lat and lon):
            continue

        try:
            lat = float(lat)
            lon = float(lon)
        except ValueError:
            continue

        entity = feed.entity.add()
        entity.id = f"veh_{plate.replace(' ', '')}_{route_code}"
        
        # Vehicle Position
        entity.vehicle.position.latitude = lat
        entity.vehicle.position.longitude = lon
        
        # Vehicle Descriptor
        entity.vehicle.vehicle.id = plate
        entity.vehicle.vehicle.label = plate
        
        # Trip Descriptor
        # To match static GTFS trips generated by builder.py
        trip_id = f"trip_{route_code}_{direction}"
        entity.vehicle.trip.trip_id = trip_id
        entity.vehicle.trip.route_id = str(route_code)
        
        # We can also add timestamp if the API provided it, 
        # but E-Komobil seems to return just positions. We'll use current time.
        entity.vehicle.timestamp = int(time.time())

    try:
        with open(pb_path, "wb") as f:
            f.write(feed.SerializeToString())
        print(f"[{datetime.now()}] GTFS-RT VehiclePositions updated ({len(buses)} vehicles).")
    except Exception as e:
        print(f"[{datetime.now()}] Error writing vehicle_positions.pb: {e}")

if __name__ == "__main__":
    build_rt_feed()
